output-format: text
inherits:
  - strictness_high
  - full_pep8

autodetect: false


pylint:
  run: false
pycodestyle:
  run: false
pyflakes:
  run: false
pydocstyle:
  run: false
mccabe:
  run: false
bandit:
  run: false
dodgy:
  run: true

mypy:
  run: true
  options:
    ignore-missing-imports: true
    follow-imports: skip
